services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: shimiauth
      MYSQL_DATABASE: userauth
      MYSQL_USER: user
      MYSQL_PASSWORD: shimiauth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: